spring:
  application:
    name: netty-tcp-server


netty:
  host: 127.0.0.1
  port: 9879
  backlog: 1024
  connect-timeout: 15s
  keep-alive: true
  no-delay: false
  level: info

# 全局日志级别
logging:
  level:
    root: info